### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by HurtsAsHell** [xt9/DeepMobLearning#62]
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=has_entity, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=deepmoblearning:simulation_chamber, properties=[facing]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at it.pierhurts.fartgen.tilentity.TileEntityGenerator.func_73660_a(TileEntityGenerator.java:99)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

Minecraft 1.12.2 if i start the server, it crash

**Comment by xt9** [comment]
Insufficient information. closed.
